//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HowLongToBeat.App.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HowLongToBeat.App.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is unofficial open-source app for howlongtobeat.com writing for fun.
        /// </summary>
        internal static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter (applied).
        /// </summary>
        internal static string AppliedFilter {
            get {
                return ResourceManager.GetString("AppliedFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average time.
        /// </summary>
        internal static string AverageTime {
            get {
                return ResourceManager.GetString("AverageTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completionist.
        /// </summary>
        internal static string Completionist {
            get {
                return ResourceManager.GetString("Completionist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feel free to contribute and describe any bugs you encounter.
        /// </summary>
        internal static string ContributeWelcomeMessage {
            get {
                return ResourceManager.GetString("ContributeWelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter game name.
        /// </summary>
        internal static string EnterGameName {
            get {
                return ResourceManager.GetString("EnterGameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter was changed, do you want to search again you current query?.
        /// </summary>
        internal static string FilterChangedMessage {
            get {
                return ResourceManager.GetString("FilterChangedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flow.
        /// </summary>
        internal static string Flow {
            get {
                return ResourceManager.GetString("Flow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string FlowType_All {
            get {
                return ResourceManager.GetString("FlowType.All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incremental.
        /// </summary>
        internal static string FlowType_Incremental {
            get {
                return ResourceManager.GetString("FlowType.Incremental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Massively Multiplayer.
        /// </summary>
        internal static string FlowType_MassivelyMultiplayer {
            get {
                return ResourceManager.GetString("FlowType.MassivelyMultiplayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multidirectional.
        /// </summary>
        internal static string FlowType_Multidirectional {
            get {
                return ResourceManager.GetString("FlowType.Multidirectional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On-Rails.
        /// </summary>
        internal static string FlowType_OnRails {
            get {
                return ResourceManager.GetString("FlowType.OnRails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point-and-Click.
        /// </summary>
        internal static string FlowType_PointAndClick {
            get {
                return ResourceManager.GetString("FlowType.PointAndClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real-Time.
        /// </summary>
        internal static string FlowType_RealTime {
            get {
                return ResourceManager.GetString("FlowType.RealTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrolling.
        /// </summary>
        internal static string FlowType_Scrolling {
            get {
                return ResourceManager.GetString("FlowType.Scrolling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn-Based.
        /// </summary>
        internal static string FlowType_TurnBased {
            get {
                return ResourceManager.GetString("FlowType.TurnBased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        internal static string Genre {
            get {
                return ResourceManager.GetString("Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string GenreType_Action {
            get {
                return ResourceManager.GetString("GenreType.Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adventure.
        /// </summary>
        internal static string GenreType_Adventure {
            get {
                return ResourceManager.GetString("GenreType.Adventure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string GenreType_All {
            get {
                return ResourceManager.GetString("GenreType.All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arcade.
        /// </summary>
        internal static string GenreType_Arcade {
            get {
                return ResourceManager.GetString("GenreType.Arcade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battle Arena.
        /// </summary>
        internal static string GenreType_BattleArena {
            get {
                return ResourceManager.GetString("GenreType.BattleArena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beat &apos;em Up.
        /// </summary>
        internal static string GenreType_BeatEmUp {
            get {
                return ResourceManager.GetString("GenreType.BeatEmUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board Game.
        /// </summary>
        internal static string GenreType_BoardGame {
            get {
                return ResourceManager.GetString("GenreType.BoardGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breakout.
        /// </summary>
        internal static string GenreType_Breakout {
            get {
                return ResourceManager.GetString("GenreType.Breakout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Game.
        /// </summary>
        internal static string GenreType_CardGame {
            get {
                return ResourceManager.GetString("GenreType.CardGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City-Building.
        /// </summary>
        internal static string GenreType_CityBuilding {
            get {
                return ResourceManager.GetString("GenreType.CityBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compilation.
        /// </summary>
        internal static string GenreType_Compilation {
            get {
                return ResourceManager.GetString("GenreType.Compilation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Educational.
        /// </summary>
        internal static string GenreType_Educational {
            get {
                return ResourceManager.GetString("GenreType.Educational", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fighting.
        /// </summary>
        internal static string GenreType_Fighting {
            get {
                return ResourceManager.GetString("GenreType.Fighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fitness.
        /// </summary>
        internal static string GenreType_Fitness {
            get {
                return ResourceManager.GetString("GenreType.Fitness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight.
        /// </summary>
        internal static string GenreType_Flight {
            get {
                return ResourceManager.GetString("GenreType.Flight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Motion Video (FMV).
        /// </summary>
        internal static string GenreType_FullMotionVideo {
            get {
                return ResourceManager.GetString("GenreType.FullMotionVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hack and Slash.
        /// </summary>
        internal static string GenreType_HackAndSlash {
            get {
                return ResourceManager.GetString("GenreType.HackAndSlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden Object.
        /// </summary>
        internal static string GenreType_HiddenObject {
            get {
                return ResourceManager.GetString("GenreType.HiddenObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horror.
        /// </summary>
        internal static string GenreType_Horror {
            get {
                return ResourceManager.GetString("GenreType.Horror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interactive Art.
        /// </summary>
        internal static string GenreType_InteractiveArt {
            get {
                return ResourceManager.GetString("GenreType.InteractiveArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        internal static string GenreType_Management {
            get {
                return ResourceManager.GetString("GenreType.Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music/Rhythm.
        /// </summary>
        internal static string GenreType_MusicRhythm {
            get {
                return ResourceManager.GetString("GenreType.MusicRhythm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open World.
        /// </summary>
        internal static string GenreType_OpenWorld {
            get {
                return ResourceManager.GetString("GenreType.OpenWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party.
        /// </summary>
        internal static string GenreType_Party {
            get {
                return ResourceManager.GetString("GenreType.Party", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pinball.
        /// </summary>
        internal static string GenreType_Pinball {
            get {
                return ResourceManager.GetString("GenreType.Pinball", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform.
        /// </summary>
        internal static string GenreType_Platform {
            get {
                return ResourceManager.GetString("GenreType.Platform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puzzle.
        /// </summary>
        internal static string GenreType_Puzzle {
            get {
                return ResourceManager.GetString("GenreType.Puzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Racing/Driving.
        /// </summary>
        internal static string GenreType_RacingDriving {
            get {
                return ResourceManager.GetString("GenreType.RacingDriving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roguelike.
        /// </summary>
        internal static string GenreType_Roguelike {
            get {
                return ResourceManager.GetString("GenreType.Roguelike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role-Playing.
        /// </summary>
        internal static string GenreType_RolePlaying {
            get {
                return ResourceManager.GetString("GenreType.RolePlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sandbox.
        /// </summary>
        internal static string GenreType_Sandbox {
            get {
                return ResourceManager.GetString("GenreType.Sandbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shooter.
        /// </summary>
        internal static string GenreType_Shooter {
            get {
                return ResourceManager.GetString("GenreType.Shooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulation.
        /// </summary>
        internal static string GenreType_Simulation {
            get {
                return ResourceManager.GetString("GenreType.Simulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social.
        /// </summary>
        internal static string GenreType_Social {
            get {
                return ResourceManager.GetString("GenreType.Social", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sports.
        /// </summary>
        internal static string GenreType_Sports {
            get {
                return ResourceManager.GetString("GenreType.Sports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stealth.
        /// </summary>
        internal static string GenreType_Stealth {
            get {
                return ResourceManager.GetString("GenreType.Stealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strategy/Tactical.
        /// </summary>
        internal static string GenreType_StrategyTactical {
            get {
                return ResourceManager.GetString("GenreType.StrategyTactical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survival.
        /// </summary>
        internal static string GenreType_Survival {
            get {
                return ResourceManager.GetString("GenreType.Survival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tower Defense.
        /// </summary>
        internal static string GenreType_TowerDefense {
            get {
                return ResourceManager.GetString("GenreType.TowerDefense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trivia.
        /// </summary>
        internal static string GenreType_Trivia {
            get {
                return ResourceManager.GetString("GenreType.Trivia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicular Combat.
        /// </summary>
        internal static string GenreType_VehicularCombat {
            get {
                return ResourceManager.GetString("GenreType.VehicularCombat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Novel.
        /// </summary>
        internal static string GenreType_VisualNovel {
            get {
                return ResourceManager.GetString("GenreType.VisualNovel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour Range.
        /// </summary>
        internal static string HourRange {
            get {
                return ResourceManager.GetString("HourRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        internal static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length Range Category.
        /// </summary>
        internal static string LengthRangeCategory {
            get {
                return ResourceManager.GetString("LengthRangeCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load failed, try again.
        /// </summary>
        internal static string LoadFailedMessage {
            get {
                return ResourceManager.GetString("LoadFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main + Extra.
        /// </summary>
        internal static string MainPlusExtra {
            get {
                return ResourceManager.GetString("MainPlusExtra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main story.
        /// </summary>
        internal static string MainStory {
            get {
                return ResourceManager.GetString("MainStory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        internal static string Max {
            get {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        internal static string Min {
            get {
                return ResourceManager.GetString("Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mins.
        /// </summary>
        internal static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No games found.
        /// </summary>
        internal static string NoGamesFoundMessage {
            get {
                return ResourceManager.GetString("NoGamesFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter (not applied).
        /// </summary>
        internal static string NotAppliedFilter {
            get {
                return ResourceManager.GetString("NotAppliedFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perspective.
        /// </summary>
        internal static string Perspective {
            get {
                return ResourceManager.GetString("Perspective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string PerspectiveType_All {
            get {
                return ResourceManager.GetString("PerspectiveType_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First-Person.
        /// </summary>
        internal static string PerspectiveType_FirstPerson {
            get {
                return ResourceManager.GetString("PerspectiveType.FirstPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isometric.
        /// </summary>
        internal static string PerspectiveType_Isometric {
            get {
                return ResourceManager.GetString("PerspectiveType.Isometric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Side.
        /// </summary>
        internal static string PerspectiveType_Side {
            get {
                return ResourceManager.GetString("PerspectiveType.Side", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string PerspectiveType_Text {
            get {
                return ResourceManager.GetString("PerspectiveType.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third-Person.
        /// </summary>
        internal static string PerspectiveType_ThirdPerson {
            get {
                return ResourceManager.GetString("PerspectiveType.ThirdPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top-Down.
        /// </summary>
        internal static string PerspectiveType_TopDown {
            get {
                return ResourceManager.GetString("PerspectiveType.TopDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Reality.
        /// </summary>
        internal static string PerspectiveType_VirtualReality {
            get {
                return ResourceManager.GetString("PerspectiveType.VirtualReality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform.
        /// </summary>
        internal static string Platform {
            get {
                return ResourceManager.GetString("Platform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string PlatformType_All {
            get {
                return ResourceManager.GetString("PlatformType.All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emulated.
        /// </summary>
        internal static string PlatformType_Emulated {
            get {
                return ResourceManager.GetString("PlatformType.Emulated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nintendo 3DS.
        /// </summary>
        internal static string PlatformType_Nintendo3DS {
            get {
                return ResourceManager.GetString("PlatformType.Nintendo3DS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nintendo Switch.
        /// </summary>
        internal static string PlatformType_NintendoSwitch {
            get {
                return ResourceManager.GetString("PlatformType.NintendoSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PC.
        /// </summary>
        internal static string PlatformType_PC {
            get {
                return ResourceManager.GetString("PlatformType.PC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlayStation 3.
        /// </summary>
        internal static string PlatformType_PlayStation3 {
            get {
                return ResourceManager.GetString("PlatformType.PlayStation3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlayStation 4.
        /// </summary>
        internal static string PlatformType_PlayStation4 {
            get {
                return ResourceManager.GetString("PlatformType.PlayStation4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlayStation 5.
        /// </summary>
        internal static string PlatformType_PlayStation5 {
            get {
                return ResourceManager.GetString("PlatformType.PlayStation5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlayStation Vita.
        /// </summary>
        internal static string PlatformType_PlayStationVita {
            get {
                return ResourceManager.GetString("PlatformType.PlayStationVita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wii U.
        /// </summary>
        internal static string PlatformType_WiiU {
            get {
                return ResourceManager.GetString("PlatformType.WiiU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xbox 360.
        /// </summary>
        internal static string PlatformType_Xbox360 {
            get {
                return ResourceManager.GetString("PlatformType.Xbox360", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xbox One.
        /// </summary>
        internal static string PlatformType_XboxOne {
            get {
                return ResourceManager.GetString("PlatformType.XboxOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xbox Series X/S.
        /// </summary>
        internal static string PlatformType_XboxSeriesXS {
            get {
                return ResourceManager.GetString("PlatformType.XboxSeriesXS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release year.
        /// </summary>
        internal static string ReleaseYear {
            get {
                return ResourceManager.GetString("ReleaseYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching in progress. Wait for complete.
        /// </summary>
        internal static string SearchInProgressMessage {
            get {
                return ResourceManager.GetString("SearchInProgressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds.
        /// </summary>
        internal static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort By.
        /// </summary>
        internal static string SortBy {
            get {
                return ResourceManager.GetString("SortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string SortCategoryType_Name {
            get {
                return ResourceManager.GetString("SortCategoryType.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Popular.
        /// </summary>
        internal static string SortCategoryType_Popular {
            get {
                return ResourceManager.GetString("SortCategoryType.Popular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Date.
        /// </summary>
        internal static string SortCategoryType_ReleaseDate {
            get {
                return ResourceManager.GetString("SortCategoryType.ReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Rated.
        /// </summary>
        internal static string SortCategoryType_TopRated {
            get {
                return ResourceManager.GetString("SortCategoryType.TopRated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View github repo.
        /// </summary>
        internal static string ViewGithubRepository {
            get {
                return ResourceManager.GetString("ViewGithubRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year of release: {0}.
        /// </summary>
        internal static string YearOfRelease {
            get {
                return ResourceManager.GetString("YearOfRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
